# Generated by Django 4.2.6 on 2024-03-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='custom_field',
            field=models.CharField(default='Default fiels', max_length=100),
            preserve_default=False,
        ),
    ]
