# Generated by Django 4.2.6 on 2024-03-17 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_prince'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='prince',
        ),
    ]
